"""empty message

Revision ID: 47e00545e316
Revises: 78d52e81ce37
Create Date: 2025-01-06 22:41:56.245704

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "47e00545e316"
down_revision = "78d52e81ce37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profile_image", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("profile_image")

    # ### end Alembic commands ###
