"""empty message

Revision ID: 4fb70eabeaa6
Revises: b6c9a275ac58
Create Date: 2025-01-09 09:08:14.731031

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4fb70eabeaa6"
down_revision = "b6c9a275ac58"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("film", schema=None) as batch_op:
        batch_op.drop_column("backdrop_path")
        batch_op.drop_column("poster_path")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("film", schema=None) as batch_op:
        batch_op.add_column(sa.Column("poster_path", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("backdrop_path", sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
