"""empty message

Revision ID: 54ccaba75dbf
Revises: e46d0816d896
Create Date: 2025-01-18 08:29:16.187226

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "54ccaba75dbf"
down_revision = "e46d0816d896"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_collection_name_user", ["name", "user_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.drop_constraint("uq_collection_name_user", type_="unique")

    # ### end Alembic commands ###
