"""empty message

Revision ID: 61659d845fc6
Revises: 78d52e81ce37
Create Date: 2025-01-06 20:29:16.084117

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "61659d845fc6"
down_revision = "78d52e81ce37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profile_image", sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("profile_image")

    # ### end Alembic commands ###
