"""empty message

Revision ID: b6318f877761
Revises: 47e00545e316
Create Date: 2025-01-07 15:06:58.166322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6318f877761'
down_revision = '47e00545e316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_collection')
    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('film_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'film', ['film_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('film_id')

    op.create_table('film_collection',
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('collection_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_item_id'], ['collection_item.id'], name='film_collection_collection_item_id_fkey'),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name='film_collection_film_id_fkey'),
    sa.PrimaryKeyConstraint('film_id', 'collection_item_id', name='film_collection_pkey')
    )
    # ### end Alembic commands ###
