"""empty message

Revision ID: b6c9a275ac58
Revises: 47e00545e316
Create Date: 2025-01-08 16:17:55.216157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c9a275ac58'
down_revision = '47e00545e316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backdrop_path', sa.String(), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('backdrop_path')

    # ### end Alembic commands ###
