"""empty message

Revision ID: e12a565b1437
Revises: 54ccaba75dbf
Create Date: 2025-01-18 09:34:05.281357

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e12a565b1437"
down_revision = "54ccaba75dbf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collection_item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.alter_column("collection_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])
        batch_op.drop_column("in_wishlist")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collection_item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("in_wishlist", sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("collection_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
