"""empty message

Revision ID: e46d0816d896
Revises: 4fb70eabeaa6
Create Date: 2025-01-09 11:07:12.789184

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e46d0816d896"
down_revision = "4fb70eabeaa6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("film_collection")
    with op.batch_alter_table("collection_item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("collection_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("film_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint("collection_item_user_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(None, "film", ["film_id"], ["id"])
        batch_op.create_foreign_key(None, "collection", ["collection_id"], ["id"])
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collection_item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key("collection_item_user_id_fkey", "user", ["user_id"], ["id"])
        batch_op.drop_column("film_id")
        batch_op.drop_column("collection_id")

    op.create_table(
        "film_collection",
        sa.Column("film_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("collection_item_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_item_id"], ["collection_item.id"], name="film_collection_collection_item_id_fkey"
        ),
        sa.ForeignKeyConstraint(["film_id"], ["film.id"], name="film_collection_film_id_fkey"),
        sa.PrimaryKeyConstraint("film_id", "collection_item_id", name="film_collection_pkey"),
    )
    op.drop_table("collection")
    # ### end Alembic commands ###
