services:
  api:
    build: .
    ports:
      - 8002:5000
    volumes:
      - ./:/app/filmy
    working_dir: /app/filmy/app
    command: flask run --debug --host=0.0.0.0 & python3 /app/filmy/app/app.py
    environment:
      POSTGRESQL_CONFIG: ""
      SQLALCHEMY_TRACK_MODIFICATIONS: False
      MOVIE_DB_TOKEN: ''
      JWT_SECRET_KEY: ""
      SECRET_KEY: ""
      JWT_ACCESS_TOKEN_EXPIRES: 1
      FRONT_URL: ''
    depends_on:
      db:
        condition: service_healthy
    depends_on:
      - db
    networks:
      - filmy_network
  db:
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: filmy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    networks:
        - filmy_network

networks:
  filmy_network:
    name: filmy_network