services:
  api:
    build: .
    ports:
      - 8001:5000
    volumes:
      - ./api:/app/api
    command: flask --app api.app run --debug --host=0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: filmy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres