services:
  api:
    build: .
    ports:
      - 8002:5000
    volumes:
      - ./:/app/filmy
    working_dir: /app/filmy/app
    command: flask run --debug --host=0.0.0.0 & python3 /app/filmy/app/app.py
    depends_on:
      - db
    networks:
      - filmy_network
  db:
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: filmy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
        - filmy_network

networks:
  filmy_network:
    name: filmy_network