services:
  api:
    build: .
    ports:
      - 8001:5000
    volumes:
      - ./app:/app
    command: flask run --debug --host=0.0.0.0
    depends_on:
      - db
    networks:
      - filmy_network
  db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: filmy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
        - filmy_network

networks:
  filmy_network:
    name: filmy_network